require: rubocop-rails
AllCops:
  NewCops: enable
  SuggestExtensions: false
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**
    - config/**
    - script/**
Documentation:
  Enabled: false