require: rubocop-rails
AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Max: 25